### ISSUE TITLE
PRs worth to be merged

### ISSUE THREAD

**Issue by sphh** [driscollis/ObjectListView3#1]
I installed `ObjectListView3` and run into a couple of issues, where were already dealt with with previous PRs. Could you merge them?

- https://github.com/eriknystrom/ObjectListView2/pull/8/
- https://github.com/eriknystrom/ObjectListView2/pull/10/
- https://github.com/EccentricTom/ObjectListView2/commit/41ed5b0daa726382fc235b97b11cece385c9e7b6 (which IMHO is better than https://github.com/eriknystrom/ObjectListView2/pull/11/ or https://github.com/eriknystrom/ObjectListView2/pull/9/)

(I only included the very first occurrence, if an change has been proposed more than once.)

**Comment by driscollis** [comment]
Looks like I can't (or don't know how to) merge these into OLV3 since they are pointed at OLV2. I'll have to copy the changes over manually to get them in.

**Comment by sphh** [comment]
A pity, because the authorship will get lost :confounded: Fortunately they are small changes to be handcrafted into the existing code base.

**Comment by eriknystrom** [comment]
Would it be possible for me to merge them into olv2 then rebase olv3 onto that? Keeps the authorship and would just allow for the rename to go over the top?

**Comment by driscollis** [comment]
Maybe. I just got the ListItemAttr one in though. I guess I'm too gung ho. But we can certainly do that for the other one

**Comment by sphh** [comment]
I would not know. My git knowledge is just very, very rudimentary … Personally I would ask those authors, if they want to make a PR against `ObjectListView3`. If they don't care, I would just include the patches (and mention it somewhere)

**Comment by driscollis** [comment]
Well I did the floor division myself last year for a hackathon...so that's also my bad. 

Anyway, are you saying you have merged those PRs and I can rebase mine on olv2 or are you saying something else?

**Comment by eriknystrom** [comment]
Yes, I merged the relevant PRs so you can rebase for authorship continuity or continue to cherry-pick to make the commits cleaner.

**Comment by driscollis** [comment]
I may just keep cherry-picking. My git client is basically crashing trying to rebase and I guess my git skills aren't good enough to figure out what the deal is

**Comment by sphh** [comment]
May I add my 2¢ opinion to the integer stuff (please keep in mind, I lost track, which one has now been implemented):

1. I would think, that `int(a / b)` would be slower than `a // b` and would not give any advantages.
2. Re `math.ceil()`: Is it really worth importing an additional package just for this? Maybe a `sz.GetHeight() // 3 + 1` is sufficient? (Alternatively use `-(-sz.GetHeight() // 3) # Emulate math.ceil(a/b)`; see https://stackoverflow.com/questions/17140332/implementing-ceil-function-without-using-if-else#answer-58253356)

**Comment by driscollis** [comment]
If you are referring to `_HandleSize`, I believe I used the `//` implementation

**Comment by sphh** [comment]
Actually I meant all places, where the `wx` methods requires an `int`. I believe, you have covered them! :+1: 

I am not sure about setting the height of the replacement text, because I do not know, where the `3` comes from …

**Comment by driscollis** [comment]
Okay. I don't know where that came from originally either and the original authors aren't around to ask. I am going to close this though since I think I got everything in there. Feel free to re-open if I missed something or create a new issue though

**Comment by sphh** [comment]
Thanks for your work!!
